---

- name: Install the common packages
  apt: name={{ item }} update_cache=yes cache_valid_time=7200 state=present
  with_items:
   - htop
   - vim
   - iftop
   - iotop
   - ngrep
   - tree
   - curl
   - ssh
   - git
   - acl
   - catdoc
  tags: common

- name: Install the additional packages
  apt: name={{ item }} state=present
  with_items: common.additional_packages
  tags: common
  when: common.additional_packages is defined

- name: Copy the bashrc files
  template: src=.bashrc.j2 dest=/root/.bashrc
  tags: common

- name: Copy the vim configuration
  copy: src=.vimrc dest=/root/.vimrc
  tags: common
